services:
  kafka:
    image: confluentinc/cp-kafka:7.8.3
    container_name: kafka
    ports:
      - "9092:9092"

    environment:
      KAFKA_KRAFT_MODE: 'true'

      CLUSTER_ID: '1L6g7nGhU-eAKfL--X25wo'
      KAFKA_NODE_ID: 1

      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs

    volumes:
      - kafka_kraft:/var/lib/kafka/data

    healthcheck:
      test: [ "CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092 > /dev/null 2>&1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - data:/usr/share/elasticsearch/data

    healthcheck:
      test: ["CMD-SHELL", "curl -fs 'http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=0s' > /dev/null"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy

  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"

    healthcheck:
      test: [ "CMD-SHELL", "mongosh --quiet --eval 'db.runCommand({ ping: 1 })' > /dev/null" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  data_handler:
    build: ./data_handling_and_producing
    container_name: data_handler
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      ES_URI: http://elasticsearch:9200
    volumes:
      - C:/army_podcasts:/army_podcasts
    depends_on:
      - data_consumer

  data_consumer:
    build: ./consuming and db
    container_name: data_consumer
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      ES_URI: http://elasticsearch:9200
      MONGO_URI: mongodb://mongo:27017/
    depends_on:
      - stt

  stt:
    build: ./STT
    container_name: stt
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      ES_URI: http://elasticsearch:9200

    depends_on:
      - text_analyzer

  text_analyzer:
    build: ./text_analyzer
    container_name: text_analyzer
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      ES_URI: http://elasticsearch:9200

    depends_on:
      elasticsearch:
        condition: service_healthy


volumes:
  kafka_kraft:
  data: